server/db/models/user.js
=> inital user table

package-lock.json, server/db/models/review.js
Review model file added to the models folder.
=> review model added

server/db/models/product.js
=> added product model

seed.js, server/db/db.js, server/db/index.js
Added the dummy data for our seed
=> added dummy data to db

script/seed.js, server/db/index.js, server/db/models/index.js
=> fixes errors

server/db/models/user.js
=> added name and address columns to the user table

server/api/index.js, server/api/products.js
=> added GET routes for products

script/seed.js, server/db/models/user.js
=> fixed seed file to include user name and address

package-lock.json
=> added dev branch

server/db/models/cart.js, server/db/models/index.js
=> created cart table

client/routes.js, server/api/cart.js, server/db/models/cart.js, server/db/models/index.js, server/index.js
=> Cart setup

client/components/all-products.js, client/components/index.js, client/components/navbar.js, client/routes.js, client/store/index.js, client/store/productReducer.js, package-lock.json, public/style.css, server/api/index.js, server/api/products.js, server/db/models/product.js
=> all products page complete - #20

client/components/navbar.js, client/routes.js
=> added view of all products to home page

server/db/models/index.js
=> removed purchases from exports

server/db/models/cart.js, server/db/models/index.js
=> moved quanity from cart to cartproducts

client/components/cart.js, client/components/navbar.js, client/routes.js, client/store/productReducer.js, server/db/models/index.js
=> cart component start

server/db/models/index.js
=> fixed typo

script/seed.js, server/db/models/index.js
=> edited seed to include cart items

server/api/cart.js
i got a post route working for our cart. instead of running through an array in the back end, i think we will have to do that on the front end (if at all). this does it one at a time. i still could not find that secret method but we get an item added
=> Post route irene

package-lock.json, package.json
Oauth seems to be working fine. You can login using your google credentials.
Also deleted the 'material-ui' from the dependencies since we will no longer use it.
=> oauth working. google id added

client/components/all-products.js, client/components/cart.js, client/components/checkout.js, client/store/productReducer.js, server/api/cart.js
accidentally merged my last pull request with master, so you all don't have my checkout changes including the add to cart callback stuff
this should undo that
=> closes current cart

client/components/all-products.js, client/components/category.js, client/components/single-product.js, client/routes.js
=> fixed category

server/api/cart.js
=> Guest cart irene

client/components/all-products.js, client/components/allReviews.js, client/components/review-form.js, client/components/single-product.js, client/store/reviewReducer.js, package-lock.json
The posted reviews show up on the single product page. Needs better formatting but the data is there.
=> posted reviews show up on single product page

script/seed.js, server/api/cart.js, server/api/orders.js, server/db/models/cart.js
=> fix capital letters

client/components/addProduct.js, client/components/checkout.js, client/components/index.js, client/components/manage-products.js, client/routes.js, client/store/productReducer.js, server/api/cart.js
can now add a new product
also fixes checkout so that it turns the cart to pending and assigns the proper userid
=> Tuesday night

client/components/cart.js, client/components/manage-single-order.js, client/components/navbar.js, package-lock.json, public/style.css, script/seed.js, server/api/orders.js, server/api/products.js
=> updated seed and stuff
